version: '3'

services:
  backend:
    build:
      ./backend
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/src:/app/src
    depends_on:
      - db
    ports:
    - '3000:3000'
  frontend:
    build:
      ./frontend
    volumes:
      - ./frontend/src:/app/src
    env_file:
      - ./frontend/.env
    ports:
    - '4200:4200'
  db:
    image: 'postgres'
    env_file:
      - ./backend/.env
    ports:
    - '5432:5432'
