version: '3'

services:
  backend:
    build:
      ./backend
    volumes:
      - ./backend:/app
    depends_on:
      - db
    ports:
    - '3000:3000'
  frontend:
    build:
      ./frontend
    volumes:
      - ./frontend:/app
    ports:
    - '4200:4200'
  db:
    image: 'postgres'
    ports:
    - '5432:5432'
