version: '3'

services:
  backend:
    image: sstepanov97/power-plants-backend
    env_file:
      - ../backend/.env
    depends_on:
      - db
    ports:
      - '3000:3000'
  frontend:
    image: sstepanov97/power-plants-frontend
    depends_on:
      - backend
    env_file:
      - ../frontend/.env
    ports:
      - '80:80'
  db:
    image: 'postgres'
    env_file:
      - ../backend/.env
    ports:
      - '5432:5432'
